### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by anusha7530** [Makul0/gluon#1]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

**Comment by KiranBaliga** [comment]
Please assign this task to me as a part of WOB24 @Makul0 @anusha7530 Thank you!

**Comment by Ishitagu** [comment]
hi! i would like to contribute to this issue ! please assign it to me . Thank you.

**Comment by KiranBaliga** [comment]
@Ishitagu Sorry, I already have a MD file ready for the same as I requested it earlier. :-)

**Comment by Ishitagu** [comment]
Hi @KiranBaliga,
No one has been assigned to this issue yet, and it's up to the mentor to decide who gets assigned. While I understand you have previously commented on similar issues, it’s important to note that everyone is welcome to ask for assignments, just as you have done in the past.
Let's maintain a respectful environment where we support one another. I’d appreciate it if we could avoid tagging me directly for these matters, as the mentor will handle the assignment process.
Thank you for understanding! 😊

**Comment by KiranBaliga** [comment]
@Ishitagu Yes, I clearly understand. It is upto the project owners to decide the assignment. I was developing the markdown file for the same as I assumed it was FIFO process earlier. This is my first experience so I was not sure how it is being dealt. But thanks for the insight. No offence! Happy coding! One Pull Request at a time! Best of Luck 🙏🙂

**Comment by Durgesh4993** [comment]
@Makul0 Please assign this issue to me

**Comment by Makul0** [comment]
hey everyone i am owner of the repo. do whatever you want and have fun, all the best

**Comment by Ishitagu** [comment]
@Makul0 have raise a PR, please check and merge it . thank you!

**Comment by KiranBaliga** [comment]
@Makul0 Please review the PR and share the feedback. Please add wob24 and level1 labels. Thank you 🙏

**Comment by KiranBaliga** [comment]
@Ishitagu Nice! You won! Your PR is 3 mins ahead of me, Happy Contributing! :-) Good luck! 🥳
